Courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyCourses.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

MyCourses/urls.py
from django.urls import path
from .views import HomeView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView

app_name = 'MyCourses'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_form'),
    path('mailings/edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_confirm_delete'),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <h1>Welcome to MyCourses!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div>
        <a href="{% url 'MyCourses:mailing_list' %}">View Mailings</a><br>
        <a href="{% url 'MyCourses:mailing_form' %}">Create Mailing</a><br>

    </div>
</body>
</html>